export const LandingPage = () => {
    return <>
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    Main<br />
    </>;
}